
package co.com.cetus.portal.ejb.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CustomerService", targetNamespace = "http://service.ejb.portal.cetus.com.co/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CustomerService {


    /**
     * 
     * @param findParameterRequestDTO
     * @return
     *     returns co.com.cetus.portal.ejb.service.FindParameterResponseDTO
     */
    @WebMethod
    @WebResult(name = "findParameterResponseDTO", targetNamespace = "")
    @RequestWrapper(localName = "findParameter", targetNamespace = "http://service.ejb.portal.cetus.com.co/", className = "co.com.cetus.portal.ejb.service.FindParameter")
    @ResponseWrapper(localName = "findParameterResponse", targetNamespace = "http://service.ejb.portal.cetus.com.co/", className = "co.com.cetus.portal.ejb.service.FindParameterResponse")
    public FindParameterResponseDTO findParameter(
        @WebParam(name = "findParameterRequestDTO", targetNamespace = "")
        FindParameterRequestDTO findParameterRequestDTO);

    /**
     * 
     * @param createUserRequestDTO
     * @return
     *     returns co.com.cetus.portal.ejb.service.CreateUserResponseDTO
     */
    @WebMethod
    @WebResult(name = "createUserResponseDTO", targetNamespace = "")
    @RequestWrapper(localName = "createUser", targetNamespace = "http://service.ejb.portal.cetus.com.co/", className = "co.com.cetus.portal.ejb.service.CreateUser")
    @ResponseWrapper(localName = "createUserResponse", targetNamespace = "http://service.ejb.portal.cetus.com.co/", className = "co.com.cetus.portal.ejb.service.CreateUserResponse")
    public CreateUserResponseDTO createUser(
        @WebParam(name = "createUserRequestDTO", targetNamespace = "")
        CreateUserRequestDTO createUserRequestDTO);

    /**
     * 
     * @param deleteUserRequestDTO
     * @return
     *     returns co.com.cetus.portal.ejb.service.ResponseWSDTO
     */
    @WebMethod
    @WebResult(name = "responseWSDTO", targetNamespace = "")
    @RequestWrapper(localName = "deleteUser", targetNamespace = "http://service.ejb.portal.cetus.com.co/", className = "co.com.cetus.portal.ejb.service.DeleteUser")
    @ResponseWrapper(localName = "deleteUserResponse", targetNamespace = "http://service.ejb.portal.cetus.com.co/", className = "co.com.cetus.portal.ejb.service.DeleteUserResponse")
    public ResponseWSDTO deleteUser(
        @WebParam(name = "deleteUserRequestDTO", targetNamespace = "")
        DeleteUserRequestDTO deleteUserRequestDTO);

    /**
     * 
     * @param findRolsByApplicationRequestDTO
     * @return
     *     returns co.com.cetus.portal.ejb.service.FindRolsByApplicationResponseDTO
     */
    @WebMethod
    @WebResult(name = "findRolsByApplicationResponseDTO", targetNamespace = "")
    @RequestWrapper(localName = "findRolByApplication", targetNamespace = "http://service.ejb.portal.cetus.com.co/", className = "co.com.cetus.portal.ejb.service.FindRolByApplication")
    @ResponseWrapper(localName = "findRolByApplicationResponse", targetNamespace = "http://service.ejb.portal.cetus.com.co/", className = "co.com.cetus.portal.ejb.service.FindRolByApplicationResponse")
    public FindRolsByApplicationResponseDTO findRolByApplication(
        @WebParam(name = "findRolsByApplicationRequestDTO", targetNamespace = "")
        FindRolsByApplicationRequestDTO findRolsByApplicationRequestDTO);

    /**
     * 
     * @param updateUserRequestDTO
     * @return
     *     returns co.com.cetus.portal.ejb.service.ResponseWSDTO
     */
    @WebMethod
    @WebResult(name = "responseWSDTO", targetNamespace = "")
    @RequestWrapper(localName = "updateUser", targetNamespace = "http://service.ejb.portal.cetus.com.co/", className = "co.com.cetus.portal.ejb.service.UpdateUser")
    @ResponseWrapper(localName = "updateUserResponse", targetNamespace = "http://service.ejb.portal.cetus.com.co/", className = "co.com.cetus.portal.ejb.service.UpdateUserResponse")
    public ResponseWSDTO updateUser(
        @WebParam(name = "updateUserRequestDTO", targetNamespace = "")
        UpdateUserRequestDTO updateUserRequestDTO);

    /**
     * 
     * @param findRolsByLoginRequestDTO
     * @return
     *     returns co.com.cetus.portal.ejb.service.FindRolsByLoginResponseDTO
     */
    @WebMethod
    @WebResult(name = "findRolsByLoginResponseDTO", targetNamespace = "")
    @RequestWrapper(localName = "findRolByLogin", targetNamespace = "http://service.ejb.portal.cetus.com.co/", className = "co.com.cetus.portal.ejb.service.FindRolByLogin")
    @ResponseWrapper(localName = "findRolByLoginResponse", targetNamespace = "http://service.ejb.portal.cetus.com.co/", className = "co.com.cetus.portal.ejb.service.FindRolByLoginResponse")
    public FindRolsByLoginResponseDTO findRolByLogin(
        @WebParam(name = "findRolsByLoginRequestDTO", targetNamespace = "")
        FindRolsByLoginRequestDTO findRolsByLoginRequestDTO);

    /**
     * 
     * @param validPermServiceRequestDTO
     * @return
     *     returns co.com.cetus.portal.ejb.service.ResponseWSDTO
     */
    @WebMethod
    @WebResult(name = "responseWSDTO", targetNamespace = "")
    @RequestWrapper(localName = "validPermissionService", targetNamespace = "http://service.ejb.portal.cetus.com.co/", className = "co.com.cetus.portal.ejb.service.ValidPermissionService")
    @ResponseWrapper(localName = "validPermissionServiceResponse", targetNamespace = "http://service.ejb.portal.cetus.com.co/", className = "co.com.cetus.portal.ejb.service.ValidPermissionServiceResponse")
    public ResponseWSDTO validPermissionService(
        @WebParam(name = "validPermServiceRequestDTO", targetNamespace = "http://service.ejb.portal.cetus.com.co/")
        ValidPermServiceRequestDTO validPermServiceRequestDTO);

}
